language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
  - polymer build -v
node_js: '9'
addons:
  chrome: stable
script:
  - xvfb-run polymer test --npm --module-resolution=node
dist: trusty
cache:
  directories:
    - node_modules
